// <auto-generated />
using System;
using ConferenciasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenciasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703194116_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenciasApi.Models.Asistente", b =>
                {
                    b.Property<int>("AsistenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("asistente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AsistenteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("AsistenteId");

                    b.ToTable("asistentes", (string)null);
                });

            modelBuilder.Entity("ConferenciasApi.Models.Conferencia", b =>
                {
                    b.Property<int>("ConferenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("conferencia_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConferenciaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConferenciaId");

                    b.ToTable("conferencias", (string)null);
                });

            modelBuilder.Entity("ConferenciasApi.Models.Registro", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("registro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistroId"));

                    b.Property<int>("AsistenteId")
                        .HasColumnType("integer");

                    b.Property<int>("ConferenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RegistroId");

                    b.HasIndex("AsistenteId");

                    b.HasIndex("ConferenciaId");

                    b.ToTable("registros", (string)null);
                });

            modelBuilder.Entity("ConferenciasApi.Models.Registro", b =>
                {
                    b.HasOne("ConferenciasApi.Models.Asistente", "Asistente")
                        .WithMany("Registros")
                        .HasForeignKey("AsistenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenciasApi.Models.Conferencia", "Conferencia")
                        .WithMany("Registros")
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistente");

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenciasApi.Models.Asistente", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("ConferenciasApi.Models.Conferencia", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
